### ISSUE TITLE
Add New Project to existing solution wiped the solution.

### ISSUE THREAD

**Issue by ghost** [andfomin/NgProjectTemplate#1]
Installed the template and went to add a new project to an existing solution within VS2017.  It told me that angular-cli was not installed globally (which it is) and I clicked cancel.  It proceeded then to clear out the entire solution including removing all directories within the solution.  The only thing that remained were the two protected folders .git and .vs.

**Comment by andfomin** [comment]
Thank you for your message,

Wiping out the solution folder indiscriminately on dialog cancel is a mistake. Sorry. I am going to fix it.

Regarding detection of the presence of Angular CLI, I have an idea why it failed. Can you please tell me, what Windows version is installed on your computer?

As a workaround for both of those issues, press OK anyway in the dialog. The project will be created.

**Comment by ghost** [comment]
Windows 7 Professional

**Comment by andfomin** [comment]
Commit 78b80b015de8fed3d5d5ab80e27dd4c2b2c1edb7

**Comment by andfomin** [comment]
Thank you @Lave4269

**Comment by ghost** [comment]
Awesome, good luck!
