### ISSUE TITLE
sockjs-node connection errors

### ISSUE THREAD

**Issue by Czaste** [andfomin/NgProjectTemplate#10]
Hi Andrey,

I am having an issue with the CLI connection on a project being continuously reset, over and over again. I believe that this is also preventing my application from traversing beyond the initial 'login page'. 

The application is tied to a SQL database, and when an invalid user or password is entered, the code responds correctly by stating that fact. However when a valid user/pw combo is input, and the code must traverse to another section of the code/application, it never gets there and the connect is 'bad'.

I'm not sure if this is a 'port' issue, a cross-domain issue, or something else, but at this point, after creating a fully working API project with .Net Core 2.0, after adding the item from your template the client CLI app no longer works correctly.

Any help would be appreciated. Thank you!

PS: Screen Attached

![2017-11-07](https://user-images.githubusercontent.com/19534581/32514337-b5c02b78-c3ca-11e7-898d-1b7e38f3b49d.png)

**Comment by Czaste** [comment]
So it seems that if I independently run the NG server (not within visual studio as part of the build process) in a command window that is being run as administrator, these reset issues go away.

Is there a method to allow the template version of ng serve to allow for the opening of a command window as administrator? There does not seem to be a method available to change the launchSettings.json file to allow for this when the CLI template opens 'ng serve'

**Comment by andfomin** [comment]
As I see in the browser address bar on your screenshot, the port served by the ASP.NET server is 7774. The network trace shows requests to `/sockjs-node` served by the CLI server are going to port 7774 as well. That must be a different port, 4200 by default, or whatever port the CLI serves. I don't currently know why `/sockjs-node` requests go to the wrong port.

Can you please tell me the parameter value passed to `app.UseNgProxy()` in Startup.cs?

**Comment by andfomin** [comment]
Based on your screenshot, I assume that you use Angular CLI version 1.5. There are some changes with the instantiation of an Hot Module Replacement connection in the recent version 1.5 of Angular CLI. I have changed the code in the NuGet package accordingly.

Please update the NuGet package AfominDotCom.AspNetCore.AngularCLI in your project to version 1.0.4. Simply update the package, you can keep other files intact.

@Czaste  Thank you very much for your issue report.

**Comment by Czaste** [comment]
Perhaps what I am trying to do is either not possible or not good architectural design (or both). I've updated the template (as recommended above), but there are still issues.

My goal is to have your CLI template work in the same fashion as the MSFT .Net core web template, so that both the API server and the CLI client are utilizing the same port. This setup certainly makes life easier from a coding perspective. But perhaps before the code is minified and combined, this just isn't possible. Here is the launchSettings.json file:

![untitled-1](https://user-images.githubusercontent.com/19534581/32743425-5648a558-c87a-11e7-8616-191b72cb589d.png)

With this setup, the API functions work as intended (in DEV):

![untitled-2](https://user-images.githubusercontent.com/19534581/32743541-b28b93c0-c87a-11e7-9399-c1d070ee3dc7.png)

But the client application itself still does not work properly (421 or 405 errors) because it looks like the ng server is looking at port 4200:

![2017-11-13 3](https://user-images.githubusercontent.com/19534581/32743730-3a6ceb0e-c87b-11e7-8df9-b64ac655a046.png)

Is there a way to control this issue (with your template) with a parameter, or am I just approaching this issue incorrectly?

Thanks!

**Comment by andfomin** [comment]
As far as I see, you can access the ASP.NET Core Web API at **localhost:4300/api/** and the Angular app at **localhost:4300/**. I assume you have `baseHref="/"` in .angular-cli.json. The routing looks good to me.

Please ignore those 421 and 405 status code errors for a while. They are related to the Hot Module Replacement connection establishment in the CLI and not to your application code. I am going to address that issue in the next version.

**Comment by andfomin** [comment]
NuGet package AfominDotCom.AspNetCore.AngularCLI version 1.0.5 supports the WebSocket transport for Hot Module Replacement. Simply update the NuGet package and add `app.UseWebSockets()` in Startup.cs as described in the Readme.md in this repository.

**Comment by Czaste** [comment]
Thanks Andrey! I will give it a try. The 421's were preventing the loading of an alternate/child module, so after login no other pages could be referenced.

I'll let you know how it goes.
