### ISSUE TITLE
API routing?

### ISSUE THREAD

**Issue by RobertPaulson90** [andfomin/NgProjectTemplate#11]
How to setup routing so I can communicate with ASP.NET Web API's in /api/* - anything else should go to Angular.

**Comment by Czaste** [comment]
Also same problem -- when running via VS without debugging, cannot get port designation to work, and ng serve opens command prompt as NON-administrator, which breaks CLI application (see open issue 10)

**Comment by andfomin** [comment]
Make sure `app.UseMvc()` is placed before `app.UseNgProxy()` and `app.UseNgRoute()` in `Statup.Configure()`. and also make sure you specified `"baseHref": "/"` in `.angular-cli.json`. You can find instructions in the `Readme_AngularCLI.txt` file installed by the item template.

You can test routing by entering the URL directly in the browser address bar.

**Comment by RobertPaulson90** [comment]
I had app.UseMvc() afterwards. Thanks. Will try again.
