### ISSUE TITLE
Item Template question

### ISSUE THREAD

**Issue by Stan92** [andfomin/NgProjectTemplate#13]
Hi, 
It should be a silly question.
I follow the documentation.
Starting with an .net core 2 projet, adding a Angular Cli template.
I checked the baseHref within the .angular-cli.json (was already set).
Hit F5 and add /ng at the end of the url..
I got several 404 errors from the console (in fact, it seems the angular app was not compiled/generated).
Did I miss something?
Thanks once, for sharing the extension and twice for your support..

**Comment by andfomin** [comment]
Do you see the Command Prompt window executing "ng serve" launched after you hit F5? Try to open a Command Prompt window manually, change the working directory to the project's root and run "npm start". Can you load the Angular app in the browser directly at http://localhost:4200 ?

**Comment by Stan92** [comment]
My bad, I had a project running in another window
Everything works great. thanks.
