### ISSUE TITLE
Angular 6 has changed .angular-cli.json to angular.json

### ISSUE THREAD

**Issue by simeyla** [andfomin/NgProjectTemplate#16]
Been using your project for quite some time now. 

Unfortunately it broke with Angular 6 where `.angular-cli.json` no longer exists.

Can you suggest if this is easy to update, or will this be quite involved?

**Comment by andfomin** [comment]
I will look into it soon.

**Comment by simeyla** [comment]
Thanks. I ended up switching to the guidance for Angular in ASPNET Core 2.1.

It seems to be very similar to what your project does, eg.

     spa.UseProxyToSpaDevelopmentServer("http://localhost:4200");

As my app becomes more complicated I'm finding much better performance overall by just starting up the CLI myself and compiling the .NET code separately for which the above suffices.

Thanks again for posting the project - it definitely helped me for the past few months.

https://docs.microsoft.com/en-us/aspnet/core/spa/angular?view=aspnetcore-2.1&tabs=visual-studio
