### ISSUE TITLE
On publish it puts everything in the same folder

### ISSUE THREAD

**Issue by dcuadra** [andfomin/NgProjectTemplate#17]
I only have one problem that is when I publish.
It first execute ng build and makes the directory dist with the assets inside and other folders.
After that it moves all the files to the wwwroot folder and puts all the files in the same folder without the assets and the others.
Is there something I miss or I have to put in the configuration.
Thank you

**Comment by andfomin** [comment]
Please update the NuGet package AfominDotCom.AspNetCore.AngularCLI to version 1.0.7
