### ISSUE TITLE
Need solution to handle proxy config option

### ISSUE THREAD

**Issue by ddelella** [andfomin/NgProjectTemplate#4]
For those of us who need to use WebApi with out project we use the --proxy-config option to avoid CORS related error messages.  It would be nice to have an environment variable option similar to the ngServerPort where you can set a proxy file name.

The line in the AspNetToNgRedirect.cs which needs to be altered to make this work with Visual Studio is the following:
`var ngProcess = Process.Start("cmd.exe", $"/k start ng.cmd serve --proxy-config proxy.conf.json --port {ngServerPort}");`

This will get removed if I upgrade the template via NuGet unless a way to configure it elsewhere is added.

**Comment by andfomin** [comment]
@ddelella Hi David, 
Thank you for the great idea. 
I have added a new setting named ASPNETCORE_NgServeOptions.
https://github.com/andfomin/NgProjectTemplate/commit/e14baafdd6fd266934bca70eb8206e47e37de210
Please update the NuGet package and read the section [Running the project](https://github.com/andfomin/NgProjectTemplate#running-the-project) to start using the feature.

**Comment by ddelella** [comment]
Just updated my project and the new environment variable is perfect!  Thanks
