### ISSUE TITLE
Razor / .cshtml setup possible? 

### ISSUE THREAD

**Issue by VhatAmI** [andfomin/NgProjectTemplate#6]
Hello I am using your template and when I try to use razor I have some issues

I have tried the following : 

Changing project to .NET Core 2.0 (Changed back to 1.1 as it causes errors in index.d.ts that I am unsure how to resolve)

I changed index.html to index.cshtml  (Leaving the template inside the same) 
                    Page loads with : "Cannot GET /"

I added a Startup.cs and Program.cs with the .useMVC configs program errors saying two entry points 
(AspNetToNgRedirector.cs being the one Main, Program.cs being the other.)

My end goal is to add a C# project (or 2) to the solution that will serve as a backend for some data and authentication and be bound to the angular through razor pages. I've tried all sorts of templates and tutorials but yours is the closest to what I need so far, kinda new to angular and npm so I thought I'd ask in case there is something simple I am missing or what the best approach would be to add razor to this tech stack. Back to reading blogs and tutorials for me. Any help is greatly appreciated.

**Comment by andfomin** [comment]
Please open Tools -> Extensions and Updates in Visual Studio, find the template and update it to version 1.0.7. This will bring a new Item Template with the old Project Template.

Open an ASP.NET Core project or create it using the standard dialog. Select the project in Solution Explorer and press Ctrl+Shift+A to open Add New Item dialog. Find the Angular CLI Template somewhere in Visual C# Items and proceed with creation.

Sorry, there is no documentation on the new feature yet, only the Readme file that is installed in the project by the Item Template.
