### ISSUE TITLE
Breakpoint not getting hit

### ISSUE THREAD

**Issue by ghost** [andfomin/NgProjectTemplate#7]
Hi,
I have installed the Angular CLI project template.
Everything seems to work fine,howver while putting breakpoint in typescript file it's not hitting the same.

Do i need to configure somethig?

It will be great If you can comeup with something,my whole team is heavily used to VS .VS Code will be a bit of challenge to them.We use VSO/TFS as code repository,VS Code doesn't have easy integration with that.

We are quite interested in developing Angular CLI apps in VS 2017.

**Comment by andfomin** [comment]
Angular CLI / Webpack generates map files that map TypeScript files to bundled JavaScript code and can serve them to the browser. Google Chrome supports map files and is able to recognize and download them. Chrome supports debugging of the transpiled JavaScript with projecting it to the original TypeScript code using that mappings.
As of now, I have a satisfying user experience with debugging Angular apps directly in Chrome. The HMO (Hot Module Replacement) feature in Webpack, which reloads the app on change, is quite useful. I edit a TypeScript source file in the IDE. As I save it, the source is automatically updated in the Chrome debugger. Breakpoints are preserved in this scenario.
