### ISSUE TITLE
The template doesn't work with the newest version of the cli

### ISSUE THREAD

**Issue by diegomary** [andfomin/NgProjectTemplate#8]
Hi thanks for the good work, however please be informed that the template fails with the newest version of the cli 1.4

WE tested it instead wit previous versions and it works fine

Regards

Diego

**Comment by andfomin** [comment]
Thank you for your message. I will look into the problem.

**Comment by andfomin** [comment]
That's a regression issue with Angular CLI, it's described at https://github.com/angular/angular-cli/issues/7686

The new version of the template takes into account that change. Please update to the version 1.0.7.

**Comment by diegomary** [comment]
Many thanks then
